global:
  scrape_interval:     10s 
scrape_configs:
  - job_name: 'my-api-read-prometheus'
    static_configs:
    - targets: ['fiap.6nett-grupo31.service:8080']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']