name: Trigger auto deployment for fiaptech

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ Main ]
    paths:
    - '**'
    - '.github/workflows/fiaptech-AutoDeployTrigger-da9a1f97-df17-44bd-ace1-212e13474806.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FIAPTECH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FIAPTECH_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FIAPTECH_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.FIAPTECH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FIAPTECH_REGISTRY_PASSWORD }}
          containerAppName: fiaptech
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


