name: .NET Core Desktop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4      

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore
      working-directory: 6NETT-GRUPO31/
      
    - name: Build
      run: dotnet build
      working-directory: 6NETT-GRUPO31/

    - name: Test with the dotnet CLI
      run: dotnet test
      working-directory: 6NETT-GRUPO31/



        
    
    
